version: "3"

services:
  sonarqube:
    image: sonarqube
    restart: always
    ports:
      - "9000:9000"
    environment:
      # SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar