version: "3"

services:
  sonarqube:
    image: sonarqube:${TAG}
    # restart: always
    # env_file:
    #   - ./sonarqube.env
    # environment:
      # SONAR_JDBC_URL: ${SONAR_JDBC_URL}
      # SONAR_JDBC_USERNAME: ${SONAR_JDBC_USERNAME}
      # SONAR_JDBC_PASSWORD: ${SONAR_JDBC_PASSWORD}
    ports:
      - ${SONAR_PORT}:9000
  
  # sonar-scanner:
  #   image: sonarsource/sonar-scanner-cli
  #   # restart: always
  #   environment:
  #     SONAR_HOST_URL: http://${SONARQUBE_URL}
  #     SONAR_LOGIN: myAuthenticationToken
  #   volumes:
  #     - ${YOUR_REPO}:/usr/src